const initModel = {
    nextId: 3,
    instruction: 'For many students, the first year in college can be overwhelming. Besides your class schedule, there are many opportunities that will compete for your time. Setting your own priorities—knowing what is most important for you—will help you manage your time and reduce stress and anxiety. Below are a list of goals common to many college students. Identify your priority for each goal -- high, medium, or low. If you have priorities that are not listed below, you can add your own on the next page. No doubt that your priorities will change over time. That is okay. You can return and update your priorities when needed.',
    cards: [
      {
        id: 2,
        fyPriority: 'Declare my major by the end of this academic year.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 1,
        fyPriority: 'Identify the graduation requirements for the major program that I am considering.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 0,
        fyPriority: 'Achieve or maintain my grade point average.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 4,
        fyPriority: 'Increase use of on campus academic support services.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 5,
        fyPriority: 'Research and identify potential career options.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 6,
        fyPriority: 'Try a new sport or physical activity.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 7,
        fyPriority: 'Improve management of my personal finances.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 8,
        fyPriority: 'Increase communication with, and seek advice from, faculty and advisors.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 9,
        fyPriority: 'Increase communication with, and seek advice from, faculty and advisors.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 10,
        fyPriority: 'Improve my living situation.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
        },
      {
        id: 11,
        fyPriority: 'Make more friends.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 12,
        fyPriority: 'Participate in a social club.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 13,
        fyPriority: 'Improve my physical fitness.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 14,
        fyPriority: 'Reduce and manage my stress and anxiety.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 15,
        fyPriority: 'Do volunteer work.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
      {
        id: 16,
        fyPriority: 'Find and apply for a study abroad program.',
        rank: 0,
        showRank: false,
        priorityLevel: '',
        edit: false,
      },
    ],
  };

export default initModel;
